import 'package:numus/entities/category.dart';
import 'package:numus/entities/category_type.dart';
import 'package:flutter/material.dart';

class SeedService {
  Map categoriesTranslation = {
    'en': [
      "Salary",
      "Interest",
      "Bonus",
      "Transportation",
      "Household",
      "Groceries",
      "Health",
      "Education",
      "Going out",
      "Sport",
      "Bills",
      "Pets",
      "Traveling",
      "Vacations",
      "Savings account",
      "Stocks",
      "Withdraw from savings",
    ],
    'es': [
      "Salario",
      "Interés",
      "Prima",
      "Transporte",
      "Familiar",
      "Comestibles",
      "Salud",
      "Educación",
      "Salir",
      "Deporte",
      "Facturas",
      "Mascotas",
      "Viajes",
      "Vacaciones",
      "Cuenta de ahorros",
      "Acción",
      "Retirar de los ahorros",
    ],
    'fr': [
      "Salaire",
      "Intérêt",
      "Prime",
      "Transport",
      "Ménage",
      "Les courses",
      "Santé",
      "Éducation",
      "Sortir",
      "Sport",
      "Factures",
      "Animaux de compagnie",
      "Voyages",
      "Vacance",
      "Compte épargne",
      "Actions",
      "Retirer de l'épargne",
    ],
    'it': [
      "Stipendio",
      "Interesse",
      "Bonus",
      "Trasporto",
      "Domestico",
      "Drogheria",
      "Salute",
      "Formazione scolastica",
      "Uscire",
      "Sport",
      "Fatture",
      "Animali domestici",
      "Viaggi",
      "Vacanze",
      "Conto di risparmio",
      "Azioni",
      "Prelevare dal risparmio",
    ],
    'pt': [
      "Salário",
      "Juro",
      "Bônus",
      "Transporte",
      "Doméstico",
      "Mercearias",
      "Saúde",
      "Educação",
      "Saindo",
      "Esporte",
      "Faturas",
      "Animais de estimação",
      "Viagens",
      "Férias",
      "Poupança",
      "Ações",
      "Retirar da poupança",
    ],
    'ro': [
      "Salariu",
      "Dobânda",
      "Primă",
      "Transport",
      "Gospodărie",
      "Produse alimentare",
      "Sănătate",
      "Educaţie",
      "Ieșiri",
      "Sport",
      "Facturi",
      "Animale de companie",
      "Călătorii",
      "Vacanțe",
      "Cont de economii",
      "Stocuri",
      "Retrase din economii",
    ],
  };

  List<Category> getCategoriesSeed() {
    return [
      Category(
          name: categoriesTranslation['en'][0],
          icon: Icon(Icons.payments).icon.codePoint,
          color: Colors.green.value,
          type: incomeType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][1],
          icon: Icon(Icons.request_page).icon.codePoint,
          color: Colors.blue.value,
          type: incomeType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][2],
          icon: Icon(Icons.emoji_events).icon.codePoint,
          color: Colors.red.value,
          type: incomeType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][3],
          icon: Icon(Icons.commute).icon.codePoint,
          color: Colors.brown.value,
          type: expenseType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][4],
          icon: Icon(Icons.home).icon.codePoint,
          color: Colors.yellow.value,
          type: expenseType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][5],
          icon: Icon(Icons.shopping_cart).icon.codePoint,
          color: Colors.lightGreen.value,
          type: expenseType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][6],
          icon: Icon(Icons.healing).icon.codePoint,
          color: Colors.deepPurple.value,
          type: expenseType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][7],
          icon: Icon(Icons.school).icon.codePoint,
          color: Colors.lightBlue.value,
          type: expenseType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][8],
          icon: Icon(Icons.nightlife).icon.codePoint,
          color: Colors.orange.value,
          type: expenseType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][9],
          icon: Icon(Icons.sports_basketball).icon.codePoint,
          color: Colors.lightBlue.value,
          type: expenseType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][10],
          icon: Icon(Icons.lightbulb).icon.codePoint,
          color: Colors.cyan.value,
          type: expenseType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][11],
          icon: Icon(Icons.pets).icon.codePoint,
          color: Colors.redAccent.value,
          type: expenseType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][12],
          icon: Icon(Icons.map).icon.codePoint,
          color: Colors.greenAccent.value,
          type: expenseType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][13],
          icon: Icon(Icons.home).icon.codePoint,
          color: Colors.teal.value,
          type: expenseType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][14],
          icon: Icon(Icons.account_balance_wallet).icon.codePoint,
          color: Colors.lightGreen.value,
          type: savingType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][15],
          icon: Icon(Icons.trending_up).icon.codePoint,
          color: Colors.cyan.value,
          type: savingType,
          isDefault: 1),
      Category(
          name: categoriesTranslation['en'][16],
          icon: Icon(Icons.sync_alt).icon.codePoint,
          color: Colors.green.value,
          type: withdrawType,
          isDefault: 1),
    ];
  }
}
