import 'package:numus/entities/currency.dart';

final List<Currency> currencies = [
  Currency(displayName: 'United States dollar', symbol: '\$'),
  Currency(displayName: 'Euro', symbol: '€'),
  Currency(displayName: 'Japanese yen', symbol: '¥'),
  Currency(displayName: 'Pound sterling', symbol: '£'),
  Currency(displayName: 'Canadian dollar', symbol: '\$'),
  Currency(displayName: 'Swiss franc', symbol: 'CHF'),
  Currency(displayName: 'Chinese Yuan', symbol: '¥'),
  Currency(displayName: 'Hong Kong dollar', symbol: '\$'),
  Currency(displayName: 'New Zealand dollar', symbol: '\$'),
  Currency(displayName: 'Swedish Krona', symbol: 'kr'),
  Currency(displayName: 'South Korean won', symbol: '₩'),
  Currency(displayName: 'Singapore dollar', symbol: '\$'),
  Currency(displayName: 'Norwegian Krone', symbol: 'kr'),
  Currency(displayName: 'Mexican peso', symbol: '\$'),
  Currency(displayName: 'Indian rupee', symbol: '₹'),
  Currency(displayName: 'Russian ruble', symbol: '₽'),
  Currency(displayName: 'South African rand', symbol: 'R'),
  Currency(displayName: 'Turkish lira', symbol: '₺'),
  Currency(displayName: 'Romanian leu', symbol: 'lei'),

  Currency(displayName: 'United Arab Emirates Dirham', symbol: 'د.إ.'),
  Currency(displayName: 'Afghan Afghani', symbol: '؋'),
  Currency(displayName: 'Albanian Lek', symbol: 'Lek'),
  Currency(displayName: 'Armenian Dram', symbol: 'դր.'),
  Currency(displayName: 'Argentine Peso', symbol: '\$'),
  Currency(displayName: 'Australian Dollar', symbol: '\$'),
  Currency(displayName: 'Azerbaijani Manat', symbol: 'ман.'),
  Currency(displayName: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM'),
  Currency(displayName: 'Bangladeshi Taka', symbol: '৳'),
  Currency(displayName: 'Bulgarian Lev', symbol: 'лв.'),
  Currency(displayName: 'Bahraini Dinar', symbol: 'د.ب.'),
  Currency(displayName: 'Burundian Franc', symbol: 'FBu'),
  Currency(displayName: 'Brunei Dollar', symbol: '\$'),
  Currency(displayName: 'Bolivian Boliviano', symbol: 'Bs'),
  Currency(displayName: 'Brazilian Real', symbol: 'R\$'),
  Currency(displayName: 'Botswanan Pula', symbol: 'P'),
  Currency(displayName: 'Belarusian Ruble', symbol: 'руб.'),
  Currency(displayName: 'Belize Dollar', symbol: '\$'),
  Currency(displayName: 'Congolese Franc', symbol: 'FrCD'),
  Currency(displayName: 'Chilean Peso', symbol: '\$'),
  Currency(displayName: 'Colombian Peso', symbol: '\$'),
  Currency(displayName: 'Costa Rican Colón', symbol: '₡'),
  Currency(displayName: 'Cape Verdean Escudo', symbol: '\$'),
  Currency(displayName: 'Czech Republic Koruna', symbol: 'Kč'),
  Currency(displayName: 'Djiboutian Franc', symbol: 'Fdj'),
  Currency(displayName: 'Danish Krone', symbol: 'kr'),
  Currency(displayName: 'Dominican Peso', symbol: '\$'),
  Currency(displayName: 'Algerian Dinar', symbol: 'د.ج.'),
  Currency(displayName: 'Estonian Kroon', symbol: 'kr'),
  Currency(displayName: 'Egyptian Pound', symbol: 'ج.م.'),
  Currency(displayName: 'Eritrean Nakfa', symbol: 'Nfk'),
  Currency(displayName: 'Ethiopian Birr', symbol: 'Br'),
  Currency(displayName: 'Georgian Lari', symbol: 'GEL'),
  Currency(displayName: 'Ghanaian Cedi', symbol: 'GH₵'),
  Currency(displayName: 'Guinean Franc', symbol: 'FG'),
  Currency(displayName: 'Guatemalan Quetzal', symbol: 'Q'),
  Currency(displayName: 'Honduran Lempira', symbol: 'L'),
  Currency(displayName: 'Croatian Kuna', symbol: 'kn'),
  Currency(displayName: 'Hungarian Forint', symbol: 'Ft'),
  Currency(displayName: 'Indonesian Rupiah', symbol: 'Rp'),
  Currency(displayName: 'Israeli New Sheqel', symbol: '₪'),
  Currency(displayName: 'Iraqi Dinar', symbol: 'د.ع.'),
  Currency(displayName: 'Iranian Rial', symbol: '﷼'),
  Currency(displayName: 'Icelandic Króna', symbol: 'kr'),
  Currency(displayName: 'Jamaican Dollar', symbol: '\$'),
  Currency(displayName: 'Jordanian Dinar', symbol: 'د.أ.'),
  Currency(displayName: 'Kenyan Shilling', symbol: 'Ksh'),
  Currency(displayName: 'Cambodian Riel', symbol: '៛'),
  Currency(displayName: 'Comorian Franc', symbol: 'FC'),
  Currency(displayName: 'Kuwaiti Dinar', symbol: 'د.ك.'),
  Currency(displayName: 'Kazakhstani Tenge', symbol: 'тңг.'),
  Currency(displayName: 'Lebanese Pound', symbol: 'ل.ل.'),
  Currency(displayName: 'Sri Lankan Rupee', symbol: 'SL Re'),
  Currency(displayName: 'Lithuanian Litas', symbol: 'Lt'),
  Currency(displayName: 'Latvian Lats', symbol: 'Ls'),
  Currency(displayName: 'Libyan Dinar', symbol: 'د.ل.'),
  Currency(displayName: 'Moroccan Dirham', symbol: 'د.م.'),
  Currency(displayName: 'Moldovan Leu', symbol: 'MDL'),
  Currency(displayName: 'Malagasy Ariary', symbol: 'MGA'),
  Currency(displayName: 'Macedonian Denar', symbol: 'MKD'),
  Currency(displayName: 'Myanma Kyat', symbol: 'K'),
  Currency(displayName: 'Macanese Pataca', symbol: 'MOP\$'),
  Currency(displayName: 'Mauritian Rupee', symbol: 'MURs'),
  Currency(displayName: 'Malaysian Ringgit', symbol: 'RM'),
  Currency(displayName: 'Mozambican Metical', symbol: 'MTn'),
  Currency(displayName: 'Namibian Dollar', symbol: 'N\$'),
  Currency(displayName: 'Nigerian Naira', symbol: '₦'),
  Currency(displayName: 'Nicaraguan Córdoba', symbol: 'C\$'),

  Currency(displayName: 'Nepalese Rupee', symbol: 'नेरू'),
  Currency(displayName: 'Omani Rial', symbol: 'ر.ع.'),
  Currency(displayName: 'Panamanian Balboa', symbol: 'B/.'),
  Currency(displayName: 'Peruvian Nuevo Sol', symbol: 'S/.'),
  Currency(displayName: 'Philippine Peso', symbol: '₱'),
  Currency(displayName: 'Pakistani Rupee', symbol: '₨'),
  Currency(displayName: 'Polish Zloty', symbol: 'zł'),
  Currency(displayName: 'Paraguayan Guarani', symbol: '₲'),
  Currency(displayName: 'Qatari Rial', symbol: 'ر.ق.'),
  Currency(displayName: 'Serbian Dinar', symbol: 'дин.'),
  Currency(displayName: 'Rwandan Franc', symbol: 'FR'),
  Currency(displayName: 'Saudi Riyal', symbol: 'ر.س.'),
  Currency(displayName: 'Sudanese Pound', symbol: 'SDG'),
  Currency(displayName: 'Somali Shilling', symbol: 'Ssh'),
  Currency(displayName: 'Syrian Pound', symbol: 'ل.س.'),
  Currency(displayName: 'Thai Baht', symbol: '฿'),
  Currency(displayName: 'Tunisian Dinar', symbol: 'د.ت.'),
  Currency(displayName: 'Tongan Paʻanga', symbol: 'T\$'),
  Currency(displayName: 'Trinidad and Tobago Dollar', symbol: '\$'),
  Currency(displayName: 'New Taiwan Dollar', symbol: 'NT\$'),
  Currency(displayName: 'Tanzanian Shilling', symbol: 'TSh'),
  Currency(displayName: 'Ukrainian Hryvnia', symbol: '₴'),
  Currency(displayName: 'Ugandan Shilling', symbol: 'USh'),
  Currency(displayName: 'Uruguayan Peso', symbol: '\$'),
  Currency(displayName: 'Uzbekistan Som', symbol: 'UZS'),
  Currency(displayName: 'Venezuelan Bolívar', symbol: 'Bs.F.'),
  Currency(displayName: 'Vietnamese Dong', symbol: '₫'),
  Currency(displayName: 'CFA Franc BEAC', symbol: 'FCFA'),
  Currency(displayName: 'CFA Franc BCEAO', symbol: 'CFA'),
  Currency(displayName: 'Yemeni Rial', symbol: 'ر.ي.'),
  Currency(displayName: 'Zambian Kwacha', symbol: 'ZK'),
  Currency(displayName: 'Zimbabwean Dollar', symbol: 'ZWL\$'),
];
